<a href="https://colab.research.google.com/github/suhyun96/PerfectGuide/blob/master/1%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [8]:
a = np.arange(12)
a.shape=(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

np.sort(A, axis=0) -> 열만

np.sort(A, axis=1) -> 행만 

axis => 0이면 y ,, 1이면 x 


In [14]:
a=[[8,12],[7,1]]
a= np.sort(a,axis=0)
a

array([[ 7,  1],
       [ 8, 12]])

In [15]:
a=np.sort(a,axis=1)
a

array([[ 1,  7],
       [ 8, 12]])

argsort()

정렬을 하는데 sort하고 그 해당 인덱스를 반환 

즉 0 ,1 ,2 ,3 이게 인덱스인데 sort하면 원소들 위치가 바뀜 근데 그 원래 원소들의 인덱스를 반환 